package com.example.framework.demoparent.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TAccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.id
     *
     * @mbg.generated Mon Aug 13 16:26:37 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.user_name
     *
     * @mbg.generated Mon Aug 13 16:26:37 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.money
     *
     * @mbg.generated Mon Aug 13 16:26:37 CST 2018
     */
    private BigDecimal money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.age
     *
     * @mbg.generated Mon Aug 13 16:26:37 CST 2018
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.remark
     *
     * @mbg.generated Mon Aug 13 16:26:37 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.create_by
     *
     * @mbg.generated Mon Aug 13 16:26:37 CST 2018
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.create_time
     *
     * @mbg.generated Mon Aug 13 16:26:37 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.update_by
     *
     * @mbg.generated Mon Aug 13 16:26:37 CST 2018
     */
    private Long updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_account.update_time
     *
     * @mbg.generated Mon Aug 13 16:26:37 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.id
     *
     * @return the value of t_account.id
     *
     * @mbg.generated Mon Aug 13 16:26:37 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.id
     *
     * @param id the value for t_account.id
     *
     * @mbg.generated Mon Aug 13 16:26:37 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.user_name
     *
     * @return the value of t_account.user_name
     *
     * @mbg.generated Mon Aug 13 16:26:37 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.user_name
     *
     * @param userName the value for t_account.user_name
     *
     * @mbg.generated Mon Aug 13 16:26:37 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.money
     *
     * @return the value of t_account.money
     *
     * @mbg.generated Mon Aug 13 16:26:37 CST 2018
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.money
     *
     * @param money the value for t_account.money
     *
     * @mbg.generated Mon Aug 13 16:26:37 CST 2018
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.age
     *
     * @return the value of t_account.age
     *
     * @mbg.generated Mon Aug 13 16:26:37 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.age
     *
     * @param age the value for t_account.age
     *
     * @mbg.generated Mon Aug 13 16:26:37 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.remark
     *
     * @return the value of t_account.remark
     *
     * @mbg.generated Mon Aug 13 16:26:37 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.remark
     *
     * @param remark the value for t_account.remark
     *
     * @mbg.generated Mon Aug 13 16:26:37 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.create_by
     *
     * @return the value of t_account.create_by
     *
     * @mbg.generated Mon Aug 13 16:26:37 CST 2018
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.create_by
     *
     * @param createBy the value for t_account.create_by
     *
     * @mbg.generated Mon Aug 13 16:26:37 CST 2018
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.create_time
     *
     * @return the value of t_account.create_time
     *
     * @mbg.generated Mon Aug 13 16:26:37 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.create_time
     *
     * @param createTime the value for t_account.create_time
     *
     * @mbg.generated Mon Aug 13 16:26:37 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.update_by
     *
     * @return the value of t_account.update_by
     *
     * @mbg.generated Mon Aug 13 16:26:37 CST 2018
     */
    public Long getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.update_by
     *
     * @param updateBy the value for t_account.update_by
     *
     * @mbg.generated Mon Aug 13 16:26:37 CST 2018
     */
    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_account.update_time
     *
     * @return the value of t_account.update_time
     *
     * @mbg.generated Mon Aug 13 16:26:37 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_account.update_time
     *
     * @param updateTime the value for t_account.update_time
     *
     * @mbg.generated Mon Aug 13 16:26:37 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}