package com.example.framework.demoparent.mapper;

import com.example.framework.demoparent.dao.BaseDAO;
import com.example.framework.demoparent.entity.TAccount;
import com.example.framework.demoparent.entity.TAccountExample;
import com.example.framework.demoparent.entity.TAccountKey;
import java.util.List;

import com.github.pagehelper.Page;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TAccountMapper extends BaseDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Tue Aug 14 11:27:57 CST 2018
     */
    long countByExample(TAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Tue Aug 14 11:27:57 CST 2018
     */
    int deleteByExample(TAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Tue Aug 14 11:27:57 CST 2018
     */
    int deleteByPrimaryKey(TAccountKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Tue Aug 14 11:27:57 CST 2018
     */
    int insert(TAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Tue Aug 14 11:27:57 CST 2018
     */
    int insertSelective(TAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Tue Aug 14 11:27:57 CST 2018
     */
    List<TAccount> selectByExample(TAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Tue Aug 14 11:27:57 CST 2018
     */
    TAccount selectByPrimaryKey(TAccountKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Tue Aug 14 11:27:57 CST 2018
     */
    int updateByExampleSelective(@Param("record") TAccount record, @Param("example") TAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Tue Aug 14 11:27:57 CST 2018
     */
    int updateByExample(@Param("record") TAccount record, @Param("example") TAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Tue Aug 14 11:27:57 CST 2018
     */
    int updateByPrimaryKeySelective(TAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Tue Aug 14 11:27:57 CST 2018
     */
    int updateByPrimaryKey(TAccount record);

    Page<TAccount> selectPageByExample(TAccountExample example);

}