package com.example.framework.demoparent.mapper;

import com.example.framework.demoparent.entity.TAccount;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface TAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Mon Aug 13 16:26:37 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Mon Aug 13 16:26:37 CST 2018
     */
    int insert(TAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Mon Aug 13 16:26:37 CST 2018
     */
    TAccount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Mon Aug 13 16:26:37 CST 2018
     */
    List<TAccount> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Mon Aug 13 16:26:37 CST 2018
     */
    int updateByPrimaryKey(TAccount record);
}